### PR TITLE
Fix C# display issues

### PR DESCRIPTION
**Pull request by msaussac**
update value of c# selection

### CODE REVIEW

**Comment by stvhwrd** [comment]
Thanks for the PR - what's the need for this change?

**Comment by msaussac** [comment]
Just I am a c# developer, and when i filtered to c# I had C project in the list

**Comment by stvhwrd** [comment]
This is definitely a valid issue, I hadn't realized.  This closes #5 - thanks very much for the fix! 🍻

**Comment by stvhwrd** [comment]
This PR is included in version 2.6 of the Chrome extension.

**Pull request merged**
